### ISSUE TITLE
`META_HPP_ENABLE_POLY_INFO` for non-copyable classes

### ISSUE THREAD

**Issue by globberwops** [BlackMATov/meta.hpp#100] opened 2024-09-03 14:01 UTC
I am trying to reflect a hierarchy of classes, some of which are non-copyable, and some of which are abstract (cannot be constructed).

I have only used `META_HPP_ENABLE_POLY_INFO` as of now, and it fails to compile:

```
[build] /usr/include/c++/11/bits/stl_uninitialized.h: In instantiation of ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<VehicleDbEntry>*, std::vector<std::unique_ptr<VehicleDbEntry> > >; _ForwardIterator = std::unique_ptr<VehicleDbEntry>*]’:
[build] /usr/include/c++/11/bits/stl_uninitialized.h:333:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<VehicleDbEntry>*, std::vector<std::unique_ptr<VehicleDbEntry> > >; _ForwardIterator = std::unique_ptr<VehicleDbEntry>*; _Tp = std::unique_ptr<VehicleDbEntry>]’
[build] /usr/include/c++/11/bits/stl_vector.h:558:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = std::unique_ptr<VehicleDbEntry>; _Alloc = std::allocator<std::unique_ptr<VehicleDbEntry> >]’
[build] serialization/vehicle_db.h:51:7:   required from ‘static Tp& meta_hpp::uvalue::vtable_t::do_ctor(meta_hpp::uvalue&, Args&& ...) [with T = VehicleDb&; Args = {VehicleDb&}; Tp = VehicleDb]’
[build] meta.hpp/build/prefix/include/meta.hpp/meta_all.hpp:11103:29:   required from ‘meta_hpp::uvalue::uvalue(T&&) [with T = VehicleDb&; <template-parameter-1-2> = void]’
[build] meta.hpp/build/prefix/include/meta.hpp/meta_all.hpp:10494:33:   required from ‘meta_hpp::uvalue meta_hpp::detail::deref_traits<T*>::operator()(T*) const [with T = VehicleDb]’
[build] meta.hpp/build/prefix/include/meta.hpp/meta_all.hpp:11031:62:   required from ‘static meta_hpp::uvalue::vtable_t* meta_hpp::uvalue::vtable_t::get() [with Tp = VehicleDb*]’
[build] meta.hpp/build/prefix/include/meta.hpp/meta_all.hpp:10913:84:   required from ‘static Tp& meta_hpp::uvalue::vtable_t::do_ctor(meta_hpp::uvalue&, Args&& ...) [with T = VehicleDb*; Args = {VehicleDb*}; Tp = VehicleDb*]’
[build] meta.hpp/build/prefix/include/meta.hpp/meta_all.hpp:11103:29:   required from ‘meta_hpp::uvalue::uvalue(T&&) [with T = VehicleDb*; <template-parameter-1-2> = void]’
[build] serialization/vehicle_db.h:52:3:   required from here
[build] /usr/include/c++/11/bits/stl_uninitialized.h:138:72: error: static assertion failed: result type must be constructible from value type of input range
[build] /usr/include/c++/11/bits/stl_uninitialized.h:138:72: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
```

This probably relates to #67 

Cheers,
Martin

**Comment by BlackMATov** [comment] 2024-09-03 18:11
Hi Martin!

`uvalue` currently supports non-copyable classes. And is itself a non-copyable class, by the way. But it can copy itself using methods: `copy`, `has_copy_op` if the internal class is copyable of course.

I'm not sure about the problem with these compiler errors, and I don't want to mislead you with guesses. Could you show a minimal example of reproduction so that we can talk more specifically?

**Comment by globberwops** [comment] 2024-09-04 05:40
Hi Matvey, thanks for your quick reply!

I believe I managed to boil it down to the following snippet:
```
#include <memory>
#include <ranges>
#include <utility>
#include <vector>

#include <meta.hpp/meta_all.hpp>

class A {
  META_HPP_ENABLE_POLY_INFO()

 public:
  virtual ~A() = default;
  virtual auto Get() -> std::vector<int*> = 0;
  virtual void Set(std::vector<std::unique_ptr<int>>&&) = 0;
};

class B : public A {
  META_HPP_ENABLE_POLY_INFO(A)

 public:
  ~B() override = default;
  auto Get() -> std::vector<int*> override {
    auto view = std::ranges::views::transform(values_, [](auto&& value) { return value.get(); });
    return {view.begin(), view.end()};
  }

  void Set(std::vector<std::unique_ptr<int>>&& values) override { values_ = std::move(values); }

 private:
  std::vector<std::unique_ptr<int>> values_;
};

auto main() -> int {
  auto a = std::unique_ptr<A>{std::make_unique<B>()};
  auto values = std::vector<std::unique_ptr<int>>{};
  values.emplace_back(std::make_unique<int>(1));
  values.emplace_back(std::make_unique<int>(2));
  a->Set(std::move(values));
  auto result = a->Get();
  return 0;
}
```

Without `META_HPP_ENABLE_POLY_INFO` it compiles just fine.

Cheers,
Martin

**Comment by globberwops** [comment] 2024-09-04 06:42
Update: Adhering to the rule-of-six helps. I just had to `delete` the copy operations and `default` the move operations.

**Comment by BlackMATov** [comment] 2024-09-04 09:19
Oh yeah, I know this problem :-(

This happens because containers like `std::vector<T>` (and other template classes) define some methods without any compile-time constraints. And I can't check if they can be compiled on instantiation or not. For example, `std::vector<T>` has copy constructor for all `T`, even if `T` is non-copyable.

```cpp
// successfully compiled because copy constructor is defined
static_assert(std::is_copy_constructible_v<std::vector<std::unique_ptr<int>>>);

// but failed on instantiation because std::unique_ptr<int> is non-copyable
std::vector<std::unique_ptr<int>> v;
std::vector<std::unique_ptr<int>> copy_of_v = v; // compile-time error
```

Your case is more complicated, but the problem is here.

I'll think about how to make a work-around this problem without significant loss of functionality of `uvalue`. In the meantime, you can delete the copy constructor explicitly, it will help in your case (as you correctly noted in the post above)

**Comment by BlackMATov** [comment] 2024-09-05 02:35
Should be fixed in main branch :-) Can you try it in your code?

**Comment by globberwops** [comment] 2024-09-06 06:48
Now it builds just fine, even without the copy/move ctors/operators.
I will leave them in anyway to make my classes movable.

Thank you!

**Closed** 2024-09-06 07:29 UTC
Labels: bug
